### ISSUE TITLE
Example a3m folder missing 

### ISSUE THREAD

**Issue by arupmondal835** [swanss/FragFold#2]

**Comment by swanss** [comment]
Hi Arup! I added a new file `example/mmseqs2_a3m_ftsZexample/ftsZ.a3m` to the repo for debugging purposes. By default, the program checks if the a3m file already exists and only runs mmseqs2 if it does not. I put this in a new folder to avoid disrupting that.

From your earlier post, I can see that you're calling Fragfold/mmseqs.py directly, instead of running the main script or `submit_mmseqs2.sh`. Make sure that you're using an environment with the latest version of colabfold installed. `colabfold.batch.get_msa_and_templates` should be able to take arguments like a3m_lines.
